### ISSUE TITLE
Rename profile to Five Safes 

### ISSUE THREAD

**Issue by stain** [trefx/5s-crate#12]
TRE-FX meeting 2023-08-31 agreed that "Trusted Workflow Run Crate" is not the best name for this profile and to rename it back to a variant of "Five Safes RO-Crate". This task organizes this rename

Tagging @CaroleGoble to help clarify the spelling of the desired name.

Tasks:

- [x] Clarify exact desired spelling of profile name (minutes mentions _Five Safes RO-Crate_, _5 safes RO-Crates_, _5S Crate_, _5S RO-Crate_ -- previous name was  [Five Safes Crate](https://trefx.uk/trusted-wfrun-crate/0.2-DRAFT/)) (without _RO_)
- [x] Clarify corresponding short-name for profile in URLs e.g. `https://trefx.uk/5s-crate/`
- [x] Register new PID namespace to replace https://w3id.org/trusted-wfrun-crate/ e.g. `https://w3id.org/5s-crate/` 
- [x] Rename GitHub repository https://github.com/trefx/trusted-wfrun-crate for new URL e.g. `5s-crate`
- [x] Add HTML meta redirects under https://github.com/trefx/trefx.github.io/ for `trusted-wfrun-crate/` and each released version
- [x] Update menu items in https://github.com/trefx/trefx.github.io/
- [x] Update https://trefx.uk/implemention references
- [x] Update existing PIDs to new locations
- [x] Modify title and PID  [0.4-DRAFT](https://github.com/trefx/trusted-wfrun-crate/tree/main/0.4-DRAFT) to reference new profile name 
- [x] Rewrite profile content to match new name where "Trusted Workflow Run Crate" is used inline (mostly search-replace but some rephrasing)
- [x] Update examples for 0.4
- [x] Release 0.4

In addition, the meeting proposed that Workflow Run Crate could be an implementation/specialization of Five Safes RO-Crate (see #11) -- in which case this task will still be needed for publishing the general aspects of the profile, but without renaming this github repository.

**Comment by stain** [comment]
TRE-FX call 2023-09-14 decided on spelling "Five Safes RO-Crate" and short-name `5s-crate`

**Comment by stain** [comment]
New PID requested perma-id/w3id.org#3580 -- the old PID for 0.3 will redirect to the old `trusted-wfrun-crate` so its examples are consistent.

**Comment by CaroleGoble** [comment]
Terrific!
Carole


Professor Carole Goble CBE FREng FBCS CITP
Department of Computer Science
The University of Manchester,
Manchester, M13 9PL, UK

Head of Node ELIXIR-UK<https://elixiruknode.org/>

PLEASE Do not send me a calendar invite and expect me to see it. (i) Invites only work 50% of the time (ii) if they do work they do not appear as email so I don’t know they are there until it is too late.
Want me at a meeting? Email me. Don’t just silently sneak into a diary I do not use.
